---
- name: Install Docker using official script
  shell: curl -fsSL https://get.docker.com | sh
  args:
    executable: /bin/bash

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
